### ISSUE TITLE
Groom generated YAMLs

### ISSUE THREAD

**Issue by oesgalha** [pipelinit/pipelinit-cli#135]
## Context

Pipelinit currently has 25 YAML templates to generate CI pipelines, bu they were built without enforcing a code format. We should make sure the templates and generated output follows the [Prettier](https://prettier.io/) format. Also, some files use `.yml` and others the `.yaml` extension.

Finally, the generated files may contain blank lines, that we could trim:
```yaml
      - run: python -m pip install pipenv; pipenv install --dev

      - run: python -m pip install pip flake8
      - run: python -m pip install pip bandit

      # Adapts Flake8 to run with the Black formatter, using the '--ignore' flag to skip incompatibilities errors
      # Reference: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html?highlight=other%20tools#id1
      - run: pipenv run flake8 --ignore E203,E501,W503 .
      - run: pipenv run bandit -r .
```

## Goal

- Make sure every template and generated output is formatted with the latest [Prettier](https://prettier.io/)
- Standardize with `.yaml` for file extensions[^1]
- Remove blank lines from generated output

[^1]: https://yaml.org/faq.html

This could be implemented after #129 to keep it enforced
